experiment_id: "InitialCompare_Alpha0.5"
random_seed: 42
risk_free_rate: 0.01
non_iid_params:
  alpha: 0.5
fl_params:
  total_rounds: 100
  clients_per_round: 10
  local_epochs: 5
  batch_size: 64
  learning_rate: 0.01
model_params:
  alpha: 1.0
runs:
  fedprox_dp_run:
    model_type: "FedProxDP"
    mu_prox: 0.01
    dp_params:
      target_epsilon: 2.0
      target_delta: 1e-5
      clip_norm: 1.0
  fedavg_run:
    model_type: "FedAvg"
    mu_prox: 0.0
    dp_params: null
# Centralized and LocalOnly runs are handled separately or by loading results, not via this harness directly.
