def get_gcis():
    gcis = {
        'SHEL.LON': 'Energy',
        'BP.LON': 'Energy',
        'HSBA.LON': 'Financials',
        'BARC.LON': 'Financials',
        'LLOY.LON': 'Financials',
        'LGEN.LON': 'Financials',
        'PRU.LON': 'Financials',
        'AV.LON': 'Financials',
        'STAN.LON': 'Financials',
        'LSEG.LON': 'Financials',
        'SDR.LON': 'Financials',
        'ADM.LON': 'Financials',
        'GSK.LON': 'Health Care',
        'AZN.LON': 'Health Care',
        'SN.LON': 'Health Care',
        'ULVR.LON': 'Consumer Staples',
        'DGE.LON': 'Consumer Staples',
        'BATS.LON': 'Consumer Staples',
        'TSCO.LON': 'Consumer Staples',
        'IMB.LON': 'Consumer Staples',
        'RKT.LON': 'Consumer Staples',
        'RIO.LON': 'Basic Materials',
        'AAL.LON': 'Basic Materials',
        'ANTO.LON': 'Basic Materials',
        'MNDI.LON': 'Basic Materials',
        'VOD.LON': 'Communication Services',
        'BT-A.LON': 'Communication Services',
        'NG.LON': 'Utilities',
        'SSE.LON': 'Utilities',
        'SVT.LON': 'Utilities',
        'UU.LON': 'Utilities',
        'REL.LON': 'Industrials',
        'BA.LON': 'Industrials',
        'EXPN.LON': 'Industrials',
        'AHT.LON': 'Industrials',
        'SMIN.LON': 'Industrials',
        'RR.LON': 'Industrials',
        'ITRK.LON': 'Industrials',
        'SGE.LON': 'Information Technology',
        'AUTO.LON': 'Communication Services', # Classified per report note, despite some sources suggesting Technology/Retail
        'LAND.LON': 'Real Estate',
        'SGRO.LON': 'Real Estate',
        'CPG.LON': 'Consumer Discretionary',
        'NXT.LON': 'Consumer Discretionary',
        'WTB.LON': 'Consumer Discretionary',
        'IHG.LON': 'Consumer Discretionary',
        'KGF.LON': 'Consumer Discretionary',
        'JD.LON': 'Consumer Discretionary'
    }
    return gcis